### ISSUE TITLE
Add sequence to transaction builder

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/cosmos-go-wallet#5]
I would like to propose the new argument `sequence` to build transaction. With this feature, the signer client can self manage the sequence and send multiple transactions in a block without receiving `unexpected sequence error`.

A signer client currently can send only one transaction in a block since the blockchain will update account sequence after the transaction, so the sequence queried from the chain will be always wrong before the current transaction is included into a block. Therefore, I think self manage sequence is a solution for this case.

The detailed implementation is here: https://github.com/desmos-labs/cosmos-go-wallet/commit/e5ab3824cc32681a91b5b8b01bc26c9c32b0e4ce 
In addition, I build a signer client for demo to achieve the multiple transactions in a block: https://github.com/dadamu/desmos-demo/blob/main/backend/service/client.go#L163

@RiccardoM, What do you think?   If you think it is worth to do, I can create a PR for it.

**Comment by rmontagnin** [comment]
@dadamu Yes, this would be extremely useful for some cases! I think adding the ability to specify a sequence would be great!
